-- CreateTable
CREATE TABLE `Users` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(191) NOT NULL,
    `Phone` VARCHAR(191) NOT NULL,
    `Email` VARCHAR(191) NOT NULL,
    `Password` VARCHAR(191) NOT NULL,
    `ProfileImage` TEXT NOT NULL,
    `CreateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdateAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Record` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `CreateUser` INTEGER NOT NULL,
    `PetId` INTEGER NOT NULL,
    `Disease` VARCHAR(191) NOT NULL,
    `Cause` VARCHAR(191) NOT NULL,
    `Solution` VARCHAR(191) NOT NULL,
    `CreateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdateAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Images` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `RecordId` INTEGER NOT NULL,
    `Disease` VARCHAR(191) NOT NULL,
    `Cause` VARCHAR(191) NOT NULL,
    `Solution` VARCHAR(191) NOT NULL,
    `CroppedImage` TEXT NOT NULL,
    `PetName` VARCHAR(191) NOT NULL,
    `CreateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdateAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Pets` (
    `Id` INTEGER NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(191) NOT NULL,
    `Age` INTEGER NOT NULL,
    `Weight` INTEGER NOT NULL,
    `Profile` VARCHAR(191) NULL,
    `CreateAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `UpdateAt` DATETIME(3) NOT NULL,
    `Master` INTEGER NOT NULL,

    PRIMARY KEY (`Id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Record` ADD CONSTRAINT `Record_CreateUser_fkey` FOREIGN KEY (`CreateUser`) REFERENCES `Users`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Record` ADD CONSTRAINT `Record_PetId_fkey` FOREIGN KEY (`PetId`) REFERENCES `Pets`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Images` ADD CONSTRAINT `Images_RecordId_fkey` FOREIGN KEY (`RecordId`) REFERENCES `Record`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Pets` ADD CONSTRAINT `Pets_Master_fkey` FOREIGN KEY (`Master`) REFERENCES `Users`(`Id`) ON DELETE RESTRICT ON UPDATE CASCADE;
